export const mimeTypes = {
    FOLDER: 'application/vnd.google-apps.folder',
    FILE: 'application/vnd.google-apps.file',
    AUDIO: 'application/vnd.google-apps.audio',
    MP3: 'audio/mpeg',
    MP4: 'audio/mp4',
    DOCUMENT: 'application/vnd.google-apps.document',
    DRIVE_SDK: 'application/vnd.google-apps.drive-sdk',
    DRAWING: 'application/vnd.google-apps.drawing',
    FORM: 'application/vnd.google-apps.form',
    FUSIONTABLE: 'application/vnd.google-apps.fusiontable',
    JAM: 'application/vnd.google-apps.jam',
    MAP: 'application/vnd.google-apps.map',
    PHOTO: 'application/vnd.google-apps.photo',
    PRESENTATION: 'application/vnd.google-apps.presentation',
    SCRIPT: 'application/vnd.google-apps.script',
    SHORTCUT: 'application/vnd.google-apps.shortcut',
    SITE: 'application/vnd.google-apps.site',
    SPREADSHEET: 'application/vnd.google-apps.spreadsheet',
    SPREADSHEET1: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    UNKNOWN: 'application/vnd.google-apps.unknown',
    VIDEO: 'application/vnd.google-apps.video',
    ZIP: 'application/zip',
    CSV: 'text/csv',

    DROPBOX_FOLDER: 'folder',
    DROPBOX_FILE: 'file',
};
